### ISSUE TITLE
User documentation

### ISSUE THREAD

**Issue by javo222** [Minebea-Intec/zbssvn#1]
I managed to setup the plugin with ZBS and SVN but I haven't managed to make use of it. I'm not so familiar with SVN so maybe I missed something.

When do you think a minimal documentation can be available?

**Comment by jjvbsag** [comment]
Well, the zbssvn package assumes, you have a lua project, which is already checked out from a subversion repository. I cannot give a complete subversion tutorial here, this is far out of scope.

What I can provide, is a simple bash scripts, which generates a sample project within a sample repository:
```sh
#!/bin/bash
set -e
set -x
export CURDIR=$(pwd)
echo "CURDIR=${CURDIR}"

export REPODIR=${CURDIR}/svnrepo
echo "REPODIR=${REPODIR}"

rm -rf "${REPODIR}"
svnadmin create "${REPODIR}"

export REPOURL=file:///${REPODIR}
echo "REPOURL=${REPOURL}"

svn mkdir --parents -m'create example1' ${REPOURL}/example1/{trunk,tags,branches}

export WORKINGDIR=${CURDIR}/example1
rm -rf "${WORKINGDIR}"
svn co ${REPOURL}/example1/trunk ${WORKINGDIR}

echo "print('hello world')" > ${WORKINGDIR}/example.lua
svn add ${WORKINGDIR}/example.lua
svn ci -m'added example script' ${WORKINGDIR}

zbstudio ${WORKINGDIR}/ ${WORKINGDIR}/example.lua
```

After running this script in an **empty** (!) directory ZBS should startup showing the project:
![zbs-example](https://user-images.githubusercontent.com/8567887/51025286-e77ee000-158b-11e9-9e4a-c6b370caf16a.png)

If you then move your mouse pointer over the different icons in the pending changes tab, there should be tool tips for every icon showing the function behind it.

Hope this is good enough for a startup

**Comment by javo222** [comment]
I looked ino this further and it works now. Thanks!
