### ISSUE TITLE
Missing "ALL checkbox" in commit dialog

### ISSUE THREAD

**Issue by javo222** [Minebea-Intec/zbssvn#2]
Hi,
I replaced my old zbssvn.lua with the new version and restarted ZBS but the checkbox doesn't appear in the commit dialog. Where is it supposed to be? I assume it is to select all files?
![image](https://user-images.githubusercontent.com/891874/60838381-d88b8a00-a1ca-11e9-987b-1d290fc82322.png)

Thanks
/Javo

**Comment by jjvbsag** [comment]
@javo222  
Can you give me more details? Which ZBS version? On which OS?

`All` should appear above the files:
![zbssvn](https://user-images.githubusercontent.com/8567887/60863769-02bc6680-a222-11e9-85d5-eab4b32a7de6.png)
It is only expected to be shown, if at least two files are affected by the operation, but this condition seams to be met in your screenshot.

**Comment by javo222** [comment]
Ok then I was looking at the right dialog. I looked into it further and it appears that I have a file called zbssvn.lua at C:\Program Files\ZeroBraneStudio\packages\zbssvn and that was the one I replaced. I located my user settings and found out another file located at C:\Users\myUser\.zbstudio\packages\zbssvn. After replacing that one the checkbox appears. 
Thanks!

**Comment by jjvbsag** [comment]
@javo222 Ok, thank you for the update.
BTW: If you have any suggestions, your welcome to share them here.
